### PR TITLE
Allowing auth secrets to be optional

### PR DESCRIPTION
**Pull request by Shm013**
Issue: #60 

* Add value secret.existingSecret for clearml chart.

* Add value clearml.existingAgentk8sglueSecret for clearml-agent chart.

* Add value clearml.existingClearmlConfigSecret for clearml-agent chart.

* Split Secret clearml-agent-conf in clearml-agent chart into two
  Secrets: clearml-agent-conf (agent.conf file) and clearml-agent-k8sglue
  (environment variables).

I have divided Secret clearml-agent-conf because I have multiple API keys for
multiple agents, but single clearml.conf for all.

### CODE REVIEW

**Comment by jkhenning** [comment]
@Shm013 thanks for this PR!
@valeriano-manassero WDYT?

**Comment by valeriano-manassero** [comment]
Iy looks good but CI is failing. I don't think it's strictly related PR itself but I need to check. Will do ASAP.

**Comment by valeriano-manassero** [comment]
Hi @Shm013 I'm not sure what happened but I see this PR closed. Can I help?

**Comment by Shm013** [comment]
@valeriano-manassero I squashed my commit and push into my branch with force - it was a mistake. I'm going to reopen PR right now.

**Pull request closed without merging**
