### PR TITLE
Helm chart fixes & improvements

### PR DESCRIPTION
**Pull request by wstarzak**
1. With tls enabled and no secretname set new secrets will be created to work with CertManager
2. Ability to load additional configs via configmaps (therefore no persistent storage needed - at least for api, not sure about the others)
3. Nodeport should not be fixed
4. Port in helper templating service url should not be quoted, lets use toString instead
5. Ability to desable agents added

Thats all right now - some more things can be tweaked but i have found time just for this.

### CODE REVIEW

**Comment by valeriano-manassero** [comment]
Checks are failing due to helm-docs not being run to produce ad updated README.md . I need to automate this part for the future, sorry.

**Comment by wstarzak** [comment]
@valeriano-manassero whatever, if you find my PR interesting merge it :+1: I can do more

**Comment by valeriano-manassero** [comment]
First I want to say thank you for the PR; for now I can't merge the PR because chart deployment is automated (as you can see in GitHub actions) and we need to pass checks before.

Moreover, in this case I think it's better to split the PR working on smaller tasks one by one (as you can see by my comments).

One thing that I would really love to add is your implementation about configmaps, can you extract a PR for that?

**Comment by wstarzak** [comment]
I am really sorry, i do not have time for this right now. But! I will split next merge requests for sure!

**Comment by valeriano-manassero** [comment]
@wstarzak I understand perfectly, we are in the same boat (also for me available time is never enough 😄 ). If you agree I'd try to extract some parts of this PR to issue a new one.

**Comment by wstarzak** [comment]
sure!

**Comment by valeriano-manassero** [comment]
Release 2.3.0 contains some of improvements that you posted.

About remaining stuff:

* A new version will come containing enable/disable switch for agent groups
* About Nodeport we can't move from fixed one for now
* About hostnames a new version is coming in days
* About TLS enable/disable for CertManager, can you pls issue another PR for it?
* 
Thanks for your time.

**Comment by valeriano-manassero** [comment]
With version 3.0.3 I refactored also Ingress rules. It would be great to eventually integrate cert-manager too (that is the only thing left from your proposals that can be integrated right now). Before going on I'd suggest to open an Issue so we can discuss the implementation.

Thank you for your efforts; I'm going to close this PR right now but I hope you will help us improve more with feedbacks.

**Pull request closed without merging**
