### PR TITLE
Issue #218

### LINKED ISSUE #218: [FeatureRequest]: make the global secrets stored in clearml-conf replaceable
In our environment we like to used SealedSecrets to make sure the secrets cannot be read by somebody else

At the moment the only way the global secrets can be replaced is by changing the values.yaml file. In order to replace the secrets  I would like to make it possible to use a personal secrets file. For instance like using the same method as has been used in the apiserver:  existingAdditionalConfigsSecret: ""

`# -- reference for files declared in existing Secret will be mounted and read by apiserver (examples in values.yaml) if not overridden by existingAdditionalConfigsConfigMap
  existingAdditionalConfigsSecret: ""`

### PR DESCRIPTION
**Pull request by tkraan**
a example to add a generic secret in stead of the existing secret.

Fixed #218

### CODE REVIEW

**Comment by tkraan** [comment]
@valeriano-manassero changed the secretKeyRef in the deployments to:
`name: {{ if .Values.clearml.existingAdditionalSecret -}} {{ default "clearml-conf" .Values.clearml.existingAdditionalSecret  | quote }} {{- else -}} "clearml-conf" {{- end }}`

**Review by valeriano-manassero — CHANGES_REQUESTED** [review]
pls check PR requirements on https://github.com/allegroai/clearml-helm-charts/blob/main/CONTRIBUTING.md#pull-requests

**Comment by valeriano-manassero** [comment]
@tkraan even without README not regenerated with `helm-docs` I tried your PR and I have some doubts about implementation style: it works but I think it's better to include ```{{ if .Values.clearml.existingAdditionalSecret -}} {{ default "clearml-conf" .Values.clearml.existingAdditionalSecret  | quote }} {{- else -}} "clearml-conf" {{- end }}``` in helper function more than having it repeated everywere.

I will try to contribute to your PR.

**Review by valeriano-manassero — APPROVED** [review]

**Comment by valeriano-manassero** [comment]
@tkraan can you pls test updated branch on your system to understand if it works like you want?

**Comment by tkraan** [comment]
> @tkraan can you pls test updated branch on your system to understand if it works like you want?

@valeriano-manassero I changed the name of the key in the values.yaml and now also changed it in _helpers.tpl. After that it was working for me

**Pull request merged**
