### PR TITLE
added clearml-serving chart

### PR DESCRIPTION
**Pull request by stefano-cherchi**
Added a basic but already tested helm chart to deploy clearml-serving on Kubernetes. The chart has been tested on a ClearML Server deployment released with version 3.8.0 of the Helm chart published in this repository.

### CODE REVIEW

**Comment by valeriano-manassero** [comment]
Thank you @stefano-cherchi ; can you pls regenerate README with latest version of helm-docs (1.10.0)?

Sorry for this, I still need to automate README generation by GH.

**Comment by valeriano-manassero** [comment]
I think we are near passing tests (it's pretty normal to get a lot of fails on new charts, at least it happens to me all the time :D ) .

I suggest to remove every `namespace: {{ .Values.namespace }}` line and related `namespace` parameter from `values.yaml` so namespace is inherited by Helm deployment.

@stefano-cherchi wdyt?

**Comment by valeriano-manassero** [comment]
Thank you so much, now we have a `serving` chart as a very good starting point to improve 👍

**Comment by stefano-cherchi** [comment]
My pleasure! Thank you for the assistance.

**Pull request merged**
