### PR TITLE
feat: make service nodePort configurable and add some doc descriptions

### PR DESCRIPTION
**Pull request by weixiao-huang**

### CODE REVIEW

**Comment by jkhenning** [comment]
@weixiao-huang can we close this?

**Comment by weixiao-huang** [comment]
Why close this? I think sometimes service nodePort is not necessary while using ClusterIP service type. So maybe this PR is considerable

**Comment by jkhenning** [comment]
@weixiao-huang I'm so sorry! - it seems a temporary GitHub issue made it look like there are no diffs in this PR 😕 

I'll let @valeriano-manassero review 🙂

**Review by valeriano-manassero — COMMENTED** [review]
PR is good from what I can see; I just wonder if it's better to setup a comment on kind installation in Readme template: https://github.com/allegroai/clearml-helm-charts/blob/bba5c0769f82bbceef707a5fb8d4dbf0ee47302d/charts/clearml/README.md.gotmpl#L40 saying that the Kind config must be adapted in case of custom node port. wdyt?

**Comment by weixiao-huang** [comment]
I add comments in README.md

**Review by valeriano-manassero — APPROVED** [review]

**Pull request merged**
