### PR TITLE
Allowing auth secrets to be optional #2

### PR DESCRIPTION
**Pull request by Shm013**
* Add value secret.existingSecret for clearml chart.

* Add value clearml.existingAgentk8sglueSecret for clearml-agent chart.

* Add value clearml.existingClearmlConfigSecret for clearml-agent chart.

* Split Secret clearml-agent-conf in clearml-agent chart into two
  Secrets: clearml-agent-conf (agent.conf file) and clearml-agent-k8sglue
  (environment variables).

### CODE REVIEW

**Comment by valeriano-manassero** [comment]
CI is still failing because README are not up to date. Can you pls simply rerun helm-docs ?

**Comment by Shm013** [comment]
helm-docs updated.

**Comment by valeriano-manassero** [comment]
This one looks good. CI failing is due an issue I have on repo when pr is coming from a fork. I'm going to check it, no worries

**Comment by Shm013** [comment]
Secret `release-name-clearml-agent-agentk8sglue-clearml-agent-k8sglue` is missing.

**Comment by valeriano-manassero** [comment]
> Secret `release-name-clearml-agent-agentk8sglue-clearml-agent-k8sglue` is missing.

Yes, we will have a new CI soon that should solve this issue. btw LGTM so I merged and charts are released. Ty!

**Comment by Shm013** [comment]
Issue: #60

**Pull request merged**
