### PR TITLE
Clearml agentk8s extra envs

### PR DESCRIPTION
**Pull request by lucacerone**
The new "clearml-agent" chart is missing the possibility to expose extra environment variables
in the agent deployments (similarly to how it's done for the API server, File Server and Clearml UI).

We need this for example to enable proxies, otherwise pip hangs while trying to install "clearml-agent" 
when the Agent K8S Glue pod is being created.

### CODE REVIEW

**Comment by jkhenning** [comment]
Hi @lucacerone , thanks for this contribution - we'll take a look at it as soon as possible 🙂 
@valeriano-manassero can you please take a look?

**Comment by valeriano-manassero** [comment]
@lucacerone can you pls try to update your local `helm-docs` to latest version [v1.11.0](https://github.com/norwoodj/helm-docs/releases/v1.11.0)) and regenerate README?

**Comment by lucacerone** [comment]
> @lucacerone can you pls try to update your local `helm-docs` to latest version [v1.11.0](https://github.com/norwoodj/helm-docs/releases/v1.11.0)) and regenerate README?

Hi @valeriano-manassero thanks for looking into it, I did it, but it keeps failing the linting step.

**Comment by lucacerone** [comment]
I complaints about trailing spaces, but I did run the flake command and it didn't show any error on my machine.

**Comment by valeriano-manassero** [comment]
> I complaints about trailing spaces, but I did run the flake command and it didn't show any error on my machine.

Initial Lint is not as strict as ct in next step, I fixed with https://github.com/allegroai/clearml-helm-charts/pull/94/commits/5f58c9fbe44bb9bfdd8dc02fd7dd4d163990bef3

Build failure is due Testing cluster being unavailable for maintenance now. PR lgtm now, I just need to fix the cluster and rerun tests. Will do by today. Ty!

**Comment by lucacerone** [comment]
Thanks!

**Comment by valeriano-manassero** [comment]
Manually tested on my env. LGTM merged. Ty so much!

**Pull request merged**
